spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5433/todo-list
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect